### ISSUE TITLE
Interface for samplers

### ISSUE THREAD

**Issue by slwu89** [adolgert/Fleck.jl#16]
When drafting #15 I thought about the benefits of enforcing a more strict interface (in code that is) for samplers. What do you think about making an abstract `AbstractSampler` supertype of all sampler types and defining the interface functions `next`, etc. for it, which must be implemented for subtypes?

**Comment by adolgert** [comment]
Yes! Do we know what the interface is yet? I want to see that we can do delayed reactions. Well, we can change the abstract base if we need to right now. BTW, the two classes, one for debugging and one that may be a "core matrix" use the same interface, just without the next() function. Then they can have other methods, like "likelihood()".

**Comment by slwu89** [comment]
Hm, I don't know if its been decided upon yet. I guess we haven't finalized it yet.

**Comment by adolgert** [comment]
I've read both Anderson's description of delayed reactions and yours, and I'm missing something basic, which is how a reaction with a delay differs from a reaction followed by a second reaction. Anderson's algorithm looks like it is a typical SSA for exponentially-distributed reactions, adding the ability for delays that are a fixed time later or, themselves, exponentially-distributed later. What am I missing? This may be a question best understood in a call.

**Comment by slwu89** [comment]
Hmm what's my description of delayed reactions? If you are referring to the docs/notes/delay.md in my other branch, I'm just going to list how existing frameworks treat delays and why they are unsuitable for general classes of models in ecology/epidemiology. A fully general system needs to let "delays" be their own counting processes, including with only atomic intensities (e.g. for the deterministic I to R transition)

**Comment by adolgert** [comment]
OK, that's what I wondered: "A fully general system needs to let `delays' be their own counting processes." This means that support for delays would happen _within_ the model, not in the sampler. To loop back to your initial comment, a more strict interface makes sense. We can go through the list of choices involved in the interface:

1. Should we pass the RNG into each call or put the RNG into the sampler at the start? We are passing it in because my past experience with thread parallelization suggests there may be more than one RNG that we use, and it would be possible to handle that outside the sampler. However, variance reduction techniques such as antithetic variables and common random numbers might work better for an RNG that's part of the sampler. I'll take a look at how to implement those to make sure they work well.
2. Should we specify the distribution as a single, truncated distribution or as a distribution and an enabling time? I went for the logically simpler one here because truncated distributions are relative to the current time, and it seemed clearer to use absolute times everywhere. This could go the other way, though.
3. Here's a big one. There is a moment when the model fires a transition. Why doesn't the sampler have a fire!() function? It totally could. Maybe not calling it fire!() but select_transition!() or something. The reason I took that out is that, from having implemented a dozen samplers, I know that none of the samplers need to be told about firing. It just works out that way. The cost to this is that you have to send the current time into each enable! and disable!, whereas the fire!() would be the only moment to really set the time in the sampler. What do you think?
4. There is always some identifier for the clock. In the mathematical symbols, it's the "i" in "f_i(t)". We allow for that to be a general type and templatize on it. Well, some Direct samplers have a possible optimization if they know there are only a fixed number of transitions. Instead of modifying the size of data structures, they set values to zero. And they can optimize when the designations are a consecutive, fixed set of numbers: that is, they become the indices of the vector of propensities. The way to account for these differences in code is to use or create types that designate the "consecutive and fixed" trait of the keys. This was used in Boost::graph for describing graph vertices, and it gets used in Julia all the time. I would suggest that we start with what we have now: typed dictionary keys, and then we make the underlying code more precise, and fast, by specifying more clearly the space of the keys.

Every little thing, man, every little thing. I'm going to focus today on what's the best way to test samplers. Maybe I can make a test harness that every sampler goes through, something more than we can afford to run as a Github unit test.

**Comment by adolgert** [comment]
Here is an example of Traits that would work for specifying the space of keys. These are traits for iterators. There's a good chance Julia has a set of Traits we can borrow for the keys: https://github.com/JuliaLang/julia/blob/ed53276f750a046c119a5580b16b80c5b0bef988/base/generator.jl#L93
